title: Tommaso Patriti
logo: /assets/img/logo.png
description: Passionate Computer Science student dedicated to the pursuit of clean and elegant code as a cornerstone of software craftsmanship.Specializing in distributed systems and microservices, I view coding not just as a technical task but as an art form to continually refine. Fueled by an unquenchable thirst for learning, I navigate challenges with the goal of mastering the delicate balance between simplicity and sophistication in code. Clean code is not just a practice but a philosophy that I bring to every project. With a commitment to continuous improvement, I aspire to create impactful solutions that not only function seamlessly but also showcase the beauty of well-crafted code.
show_downloads: true
google_analytics: GTM-NRSTX8WB
theme: jekyll-theme-minimal
